"""Initial migration.

Revision ID: 6d4cb72885bb
Revises: 
Create Date: 2024-03-12 18:49:46.457792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4cb72885bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_issued', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_returned', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('borrower_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('librarian_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_book_section', 'section', ['section_id'], ['id'])
        batch_op.create_foreign_key('fk_book_librarian', 'user', ['librarian_id'], ['user_id'])
        batch_op.create_foreign_key('fk_book_borrower', 'user', ['borrower_id'], ['user_id'])
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('librarian_id')
        batch_op.drop_column('borrower_id')
        batch_op.drop_column('section_id')
        batch_op.drop_column('content')
        batch_op.drop_column('date_returned')
        batch_op.drop_column('date_issued')

    # ### end Alembic commands ###
